// FlashMemInterface.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module FlashMemInterface (
		input  wire        clk_clk,                 //       clk.clk
		input  wire [5:0]  flash_csr_address,       // flash_csr.address
		input  wire        flash_csr_read,          //          .read
		output wire [31:0] flash_csr_readdata,      //          .readdata
		input  wire        flash_csr_write,         //          .write
		input  wire [31:0] flash_csr_writedata,     //          .writedata
		output wire        flash_csr_waitrequest,   //          .waitrequest
		output wire        flash_csr_readdatavalid, //          .readdatavalid
		input  wire        flash_mem_write,         // flash_mem.write
		input  wire [6:0]  flash_mem_burstcount,    //          .burstcount
		output wire        flash_mem_waitrequest,   //          .waitrequest
		input  wire        flash_mem_read,          //          .read
		input  wire [22:0] flash_mem_address,       //          .address
		input  wire [31:0] flash_mem_writedata,     //          .writedata
		output wire [31:0] flash_mem_readdata,      //          .readdata
		output wire        flash_mem_readdatavalid, //          .readdatavalid
		input  wire [3:0]  flash_mem_byteenable,    //          .byteenable
		input  wire        reset_reset_n            //     reset.reset_n
	);

	FlashMemInterface_intel_generic_serial_flash_interface_top_0 #(
		.DEVICE_FAMILY ("Cyclone V"),
		.CHIP_SELS     (1)
	) intel_generic_serial_flash_interface_top_0 (
		.avl_csr_address       (flash_csr_address),       // avl_csr.address
		.avl_csr_read          (flash_csr_read),          //        .read
		.avl_csr_readdata      (flash_csr_readdata),      //        .readdata
		.avl_csr_write         (flash_csr_write),         //        .write
		.avl_csr_writedata     (flash_csr_writedata),     //        .writedata
		.avl_csr_waitrequest   (flash_csr_waitrequest),   //        .waitrequest
		.avl_csr_readdatavalid (flash_csr_readdatavalid), //        .readdatavalid
		.avl_mem_write         (flash_mem_write),         // avl_mem.write
		.avl_mem_burstcount    (flash_mem_burstcount),    //        .burstcount
		.avl_mem_waitrequest   (flash_mem_waitrequest),   //        .waitrequest
		.avl_mem_read          (flash_mem_read),          //        .read
		.avl_mem_address       (flash_mem_address),       //        .address
		.avl_mem_writedata     (flash_mem_writedata),     //        .writedata
		.avl_mem_readdata      (flash_mem_readdata),      //        .readdata
		.avl_mem_readdatavalid (flash_mem_readdatavalid), //        .readdatavalid
		.avl_mem_byteenable    (flash_mem_byteenable),    //        .byteenable
		.clk_clk               (clk_clk),                 //     clk.clk
		.reset_reset           (~reset_reset_n)           //   reset.reset
	);

endmodule
